GET http://localhost:4000/notes

###
POST http://localhost:4000/add-notes
Content-Type: application/json

{
    "title": "Ayam",
    "content": "20000",
    "category" : "hutang"
}

###
PUT http://localhost:4000/edit-notes/11
Content-Type: application/json

{
  "title": "BEBEK",
  "content": "AKU INGIN MENJADI DUYUNG PLIS",
  "category" : "khayalan"
}

###
DELETE http://localhost:4000/delete-notes/3

###
# User Signup
POST http://localhost:4000/api/auth/signup
Content-Type: application/json

{
    "username": "bebek",
    "password": "migyu"
}

###
# User Login
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "username": "bebek",
    "password": "migyu"
}

###
# Get Notes (Protected Route)
GET http://localhost:4000/notes
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNzQ4OTg1NDM5LCJleHAiOjE3NDg5ODYzMzl9.6URHZYe7XEAwmqlI_oM-PzSZ8EyKSyTZB3UCscdi_Io
###
# Create Note (Protected Route)
POST http://localhost:4000/add-notes
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxMX0sImlhdCI6MTc0ODk3NjM5MSwiZXhwIjoxNzQ4OTc5OTkxfQ.uidaMmbNHV3N4pnTcOXPhC_BSHZNPNYyLPJZBT-iffI

{
    "title": "My first",
    "content": "This note is created by an authenticated user.",
    "category" : "private"
}

###
# Get Note By ID (Protected Route)
GET http://localhost:4000/notes/1
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNzQ4OTg1NDM5LCJleHAiOjE3NDg5ODYzMzl9.6URHZYe7XEAwmqlI_oM-PzSZ8EyKSyTZB3UCscdi_Io

###
# Update Note (Protected Route)
PUT http://localhost:4000/edit-notes/1
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxMX0sImlhdCI6MTc0ODk3NjM5MSwiZXhwIjoxNzQ4OTc5OTkxfQ.uidaMmbNHV3N4pnTcOXPhC_BSHZNPNYyLPJZBT-iffI


{
  "title": "Updated Secured Note",
  "content": "This note has been updated by an authenticated user.",
  "category" : "secure"
}

###
# Delete Note (Protected Route)
DELETE http://localhost:4000/delete-notes/1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxfSwiaWF0IjoxNzQ4OTYyNzg2LCJleHAiOjE3NDg5NjYzODZ9.97I1LTYhCx6Iv0Y-qwoMWQPqYwdN8DOGEVL3eWTly14
